site_name: Kebbie
repo_url: "https://github.com/FleksySDK/kebbie"
repo_name: "FleksySDK/kebbie"

theme:
  name: material
  custom_dir: docs/mkdocs
  logo: "assets/keyboard.svg"
  favicon: "assets/keyboard.svg"
  features:
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Welcome: "index.md"
  - "usage.md"
  - "emulated_keyboard.md"
  - "how_testing_is_done.md"
  - "architecture.md"
  - "emu_setup.md"
  - Code reference:
    - "public_api.md"
    - "internals.md"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: True
            show_root_full_path: False
            members_order: source

extra:
  generator: false
  version:
    provider: mike

extra_css:
  - css/mkdocstrings.css
